import telebot
from telebot import types

bot = telebot.TeleBot("5750388095:AAE_EUvhisYyL8SJ5S8QqIoYowa3ruhKmlQ", parse_mode=None)


@bot.message_handler(commands=['start'])
def start(message):
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    btn1 = types.KeyboardButton("✊ Камень")
    btn2 = types.KeyboardButton("✌️ Ножницы")
    btn3 = types.KeyboardButton("💸💵💴💶💷💰💳🪪 Бумага")

    markup.add(btn1, btn2,btn3)
    bot.send_message(message.chat.id,text="Привет я бот 'Камень, ножницы, бумага', рано или позно я получу ИИ и выйграю тебя, сейчас я слишком глуп =) \n Что бы играть тыкай кнопки".format(message.from_user), reply_markup=markup)


@bot.message_handler(content_types=['text'])
def func(message):
    if (message.text == "✌️ Ножницы"):
        bot.send_message(message.chat.id, 'Мой ответ 💵 Бумага 💵 🅰️4️⃣ Бумага  \nТы победил!!!!!!Опять ты выйграл, тебя невозможно победить'.format(message.from_user), parse_mode='html')

    elif (message.text == "💸💵💴💶💷💰💳🪪 Бумага"):
        bot.send_message(message.chat.id, 'Мой ответ ✊ Камень ✊  \nТы победил!!!!!!Ты слишком сильный, смелый и умный, прошу пощадииииииии'.format(message.from_user), parse_mode='html')

    elif (message.text == "✊ Камень"):
        bot.send_message(message.chat.id, 'Мой ответ ✌️ Ножницы ✌️   \nТы победил!!!!!!Люди высшая ступень развития цивилизации во вселенной...'.format(message.from_user), parse_mode='html')




bot.polling(none_stop=True)


